apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p6loehdmr-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p6loehdmr-java-springboot-gitops